# Generated by Django 2.2 on 2019-05-18 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('jira_id', models.CharField(blank=True, max_length=100)),
                ('confluence_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
