# Generated by Django 2.2.1 on 2019-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
