# Generated by Django 2.2.1 on 2019-05-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190520_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
    ]
