# Generated by Django 2.2.2 on 2019-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190520_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='confluence_id',
            new_name='jira_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jira_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='jira_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
