# Generated by Django 2.2.2 on 2019-06-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_done'),
        ('tasks', '0005_auto_20190617_1845'),
    ]

    operations = [
    ]
